/**
 * filter-app.js – Main UI controller for filter.html
 * Supports all 6 subjects, multi-correct filter, history stats
 */
(function(window) {
  'use strict';
  let allQuestions = [], emptySubjects = [];
  let currentFilters = { subjects: ['all'], units: ['all'], types: ['all'], difficulties: ['all'], multi: 'all', history: 'all', count: 20, random: true };
  function toBengali(num) { let bn = ['০','১','২','৩','৪','৫','৬','৭','৮','৯']; return String(num).replace(/[0-9]/g, d => bn[parseInt(d)]); }
  function getEl(id) { return document.getElementById(id); }
  function showLoading(show) { let l = getEl('loadingState'), f = getEl('filterPanel'), e = getEl('errorState'); if (show) { if(l) l.style.display = 'block'; if(f) f.style.display = 'none'; if(e) e.style.display = 'none'; } else { if(l) l.style.display = 'none'; if(f) f.style.display = 'block'; if(e) e.style.display = 'none'; } }
  function showError(msg) { let l = getEl('loadingState'), f = getEl('filterPanel'), e = getEl('errorState'), m = getEl('errorMessage'); if(l) l.style.display = 'none'; if(f) f.style.display = 'none'; if(e) e.style.display = 'block'; if(m) m.textContent = msg; }
  function updateLoadingProgress(l, t) { let p = t ? Math.round(l/t*100) : 0; let bar = getEl('progressBar'), text = getEl('progressText'); if(bar) bar.style.width = p+'%'; if(text) text.textContent = 'লোড হচ্ছে... '+toBengali(p)+'%'; }
  function createPill(label, value, group, color, extraClass) { let btn = document.createElement('button'); btn.type='button'; btn.className='filter-pill'; if(extraClass) btn.classList.add(extraClass); btn.textContent=label; btn.dataset.value=value; btn.dataset.group=group; if(color) btn.dataset.color=color; btn.addEventListener('click',()=>{ if(group==='subject') handleSubjectChange(value); else if(group==='type') handleMultiToggle('types',value,'typePills'); else if(group==='difficulty') handleMultiToggle('difficulties',value,'difficultyPills'); else if(group==='multi') handleMultiFilterChange(value); }); return btn; }
  function updatePillVisuals(containerId, selected) { let c = getEl(containerId); if(!c) return; let pills = c.querySelectorAll('.filter-pill'); for(let p of pills) { let val = p.dataset.value, isSel = selected.indexOf(val) > -1; if(isSel) { p.classList.add('active'); let col = p.dataset.color; if(col && val !== 'all') { p.style.backgroundColor = col; p.style.borderColor = col; p.style.color = 'white'; } else { p.style.backgroundColor = '#e91e63'; p.style.borderColor = '#e91e63'; p.style.color = 'white'; } } else { p.classList.remove('active'); p.style.backgroundColor = ''; p.style.borderColor = ''; p.style.color = ''; } } }
  function renderSubjectFilters() { let c = getEl('subjectPills'); if(!c || !window.FilterEngine) return; c.innerHTML = ''; c.appendChild(createPill('সব বিষয়', 'all', 'subject')); let subjects = FilterEngine.getAllSubjects(); for(let s of subjects) { let isEmpty = emptySubjects.indexOf(s) !== -1; let label = FilterEngine.getSubjectBn(s); if(isEmpty) label += ' (0)'; let pill = createPill(label, s, 'subject', FilterEngine.getSubjectColor(s), isEmpty ? 'filter-pill--empty' : ''); if(isEmpty) { pill.style.opacity = '0.6'; pill.style.textDecoration = 'line-through'; } c.appendChild(pill); } updatePillVisuals('subjectPills', currentFilters.subjects); }
  function handleSubjectChange(value) { if(value === 'all') currentFilters.subjects = ['all']; else { let allIdx = currentFilters.subjects.indexOf('all'); if(allIdx > -1) currentFilters.subjects.splice(allIdx,1); let idx = currentFilters.subjects.indexOf(value); if(idx > -1) currentFilters.subjects.splice(idx,1); else currentFilters.subjects.push(value); if(currentFilters.subjects.length === 0) currentFilters.subjects = ['all']; } currentFilters.units = ['all']; updatePillVisuals('subjectPills', currentFilters.subjects); renderUnitFilters(); updateHistoryStats(); updatePreview(); }
  function handleMultiToggle(filterKey, value, containerId) { let arr = currentFilters[filterKey]; if(value === 'all') currentFilters[filterKey] = ['all']; else { let allIdx = arr.indexOf('all'); if(allIdx > -1) arr.splice(allIdx,1); let idx = arr.indexOf(value); if(idx > -1) arr.splice(idx,1); else arr.push(value); if(arr.length === 0) currentFilters[filterKey] = ['all']; } updatePillVisuals(containerId, currentFilters[filterKey]); updatePreview(); }
  function handleMultiFilterChange(value) { currentFilters.multi = value; updatePillVisuals('multiPills', [value]); updatePreview(); }
  function renderMultiFilters() { let c = getEl('multiPills'); if(!c) return; c.innerHTML = ''; let opts = [{value:'all',label:'সব প্রশ답'},{value:'multi-only',label:'শুধু বহু-সঠিক'},{value:'single-only',label:'শুধু এককটি সঠিক'}]; opts.forEach(o => { let pill = createPill(o.label, o.value, 'multi', '#1976d2'); c.appendChild(pill); }); updatePillVisuals('multiPills', [currentFilters.multi]); }
  function renderUnitFilters() { let c = getEl('unitFilters'); if(!c || !window.FilterEngine) return; c.innerHTML = ''; let unitsBySubject = FilterEngine.getAvailableUnits(allQuestions.filter(q => emptySubjects.indexOf(q._subject) === -1), currentFilters.subjects); let subjectKeys = Object.keys(unitsBySubject); if(subjectKeys.length === 0) { c.innerHTML = '<p class="no-units-msg">কোনো অধ্যায় পাওয়া যায়নি</p>'; return; } let allPill = document.createElement('button'); allPill.type='button'; allPill.className='filter-pill'; allPill.textContent='সব অধ্যায়'; allPill.dataset.value='all'; allPill.addEventListener('click',()=>handleUnitChange('all')); c.appendChild(allPill); let useAll = currentFilters.subjects.indexOf('all') > -1 || currentFilters.subjects.length > 1; for(let subject of subjectKeys) { let units = unitsBySubject[subject]; if(useAll) { let labelDiv = document.createElement('div'); labelDiv.className='unit-group-label'; labelDiv.style.color = FilterEngine.getSubjectColor(subject); labelDiv.textContent = FilterEngine.getSubjectBn(subject); c.appendChild(labelDiv); } for(let unit of units) { let pill = document.createElement('button'); pill.type='button'; pill.className='filter-pill unit-pill'; pill.textContent = FilterEngine.getUnitBn(unit); pill.dataset.value = unit; pill.dataset.subject = subject; pill.addEventListener('click',()=>handleUnitChange(unit)); c.appendChild(pill); } } updateUnitPillVisuals(); }
  function handleUnitChange(value) { if(value === 'all') currentFilters.units = ['all']; else { let allIdx = currentFilters.units.indexOf('all'); if(allIdx > -1) currentFilters.units.splice(allIdx,1); let idx = currentFilters.units.indexOf(value); if(idx > -1) currentFilters.units.splice(idx,1); else currentFilters.units.push(value); if(currentFilters.units.length === 0) currentFilters.units = ['all']; } updateUnitPillVisuals(); updatePreview(); }
  function updateUnitPillVisuals() { let c = getEl('unitFilters'); if(!c) return; let pills = c.querySelectorAll('.filter-pill'); let selected = currentFilters.units; for(let pill of pills) { let val = pill.dataset.value; let isActive = selected.indexOf(val) > -1 || (selected.indexOf('all') > -1 && val === 'all'); if(isActive) { pill.classList.add('active'); if(val === 'all') { pill.style.backgroundColor='#e91e63'; pill.style.borderColor='#e91e63'; pill.style.color='white'; } else { let col = FilterEngine.getSubjectColor(pill.dataset.subject); pill.style.backgroundColor = col; pill.style.borderColor = col; pill.style.color = 'white'; } } else { pill.classList.remove('active'); pill.style.backgroundColor = ''; pill.style.borderColor = ''; pill.style.color = ''; } } }
  function renderTypeFilters() { let c = getEl('typePills'); if(!c) return; c.innerHTML = ''; c.appendChild(createPill('সব','all','type')); c.appendChild(createPill('তত্ত্ব','theory','type')); c.appendChild(createPill('গাণিতিক','numerical','type')); c.appendChild(createPill('মুখস্থ','memory','type')); c.appendChild(createPill('প্রয়োগ','application','type')); updatePillVisuals('typePills', currentFilters.types); }
  function renderDifficultyFilters() { let c = getEl('difficultyPills'); if(!c) return; c.innerHTML = ''; c.appendChild(createPill('সব','all','difficulty')); c.appendChild(createPill('সহজ','easy','difficulty','#4caf50')); c.appendChild(createPill('মাঝারি','medium','difficulty','#ff9800')); c.appendChild(createPill('কঠিন','hard','difficulty','#f44336')); updatePillVisuals('difficultyPills', currentFilters.difficulties); }
  function renderHistoryFilters() { let c = getEl('historyPills'); if(!c) return; c.innerHTML = ''; let opts = [{key:'all',label:'সব প্রশ্ন'},{key:'unseen',label:'নতুন (অদেখা)'},{key:'wrong',label:'ভুল হয়েছিল'},{key:'correct',label:'সঠিক হয়েছিল'},{key:'attempted',label:'আগে দিয়েছি'},{key:'never-correct',label:'কখনও সঠিক হয়নি'}]; opts.forEach(opt => { let pill = document.createElement('button'); pill.type='button'; pill.className='filter-pill'; pill.textContent=opt.label; pill.dataset.value=opt.key; pill.dataset.group='history'; pill.addEventListener('click',()=>{ currentFilters.history = opt.key; updatePillVisuals('historyPills', [opt.key]); updatePreview(); }); c.appendChild(pill); }); updatePillVisuals('historyPills', [currentFilters.history]); }
  function updateHistoryStats() { if(!window.FilterHistory) return; let statsContainer = getEl('historyStats'), bannerEl = getEl('historyBanner'), bannerTitle = getEl('historyBannerTitle'), bannerSub = getEl('historyBannerSub'), progressFill = getEl('historyProgressFill'); let filteredAll = getBaseFilteredQuestions(); let statusCounts = FilterHistory.countByStatus(filteredAll); if(statsContainer) { statsContainer.innerHTML = ''; let items = [{label:'অদেখা',count:statusCounts.unseen||0,cls:'unseen'},{label:'সঠিক',count:statusCounts.correct||0,cls:'correct'},{label:'ভুল',count:statusCounts.wrong||0,cls:'wrong'},{label:'এড়ানো',count:statusCounts.skipped||0,cls:'skipped'}]; if(statusCounts.partial) items.push({label:'আংশিক',count:statusCounts.partial,cls:'partial'}); for(let item of items) { let div = document.createElement('div'); div.className='history-stat-item'; div.innerHTML = `<span class="history-dot ${item.cls}"></span><span>${item.label}: </span><span class="history-stat-count">${toBengali(item.count)}</span>`; statsContainer.appendChild(div); } } let overallStats = FilterHistory.getOverallStats(); if(bannerEl) { if(overallStats.totalSolved > 0) { bannerEl.classList.remove('empty'); if(bannerTitle) bannerTitle.textContent = `আপনি ${toBengali(overallStats.totalSolved)}টি প্রশ্ন সম্পন্ন করেছেন`; if(bannerSub) { let totalAvail = allQuestions.filter(q => emptySubjects.indexOf(q._subject) === -1).length; let pct = totalAvail ? Math.round(overallStats.everCorrect/totalAvail*100) : 0; bannerSub.textContent = `${toBengali(overallStats.everCorrect)}টি সঠিক • ${toBengali(pct)}% সাফল্যের হার`; } if(progressFill && allQuestions.length) { let realCount = allQuestions.filter(q => emptySubjects.indexOf(q._subject) === -1).length; let fillPct = realCount ? Math.round(overallStats.totalSolved/realCount*100) : 0; progressFill.style.width = Math.min(fillPct,100)+'%'; } } else { bannerEl.classList.add('empty'); if(bannerTitle) bannerTitle.textContent = 'এখনও কোনো কুইজ দেওয়া হয়নি'; if(bannerSub) bannerSub.textContent = 'প্রথম কুইজ দিন এবং আপনার অগ্রগতি দেখুন!'; if(progressFill) progressFill.style.width = '0%'; } } }
  function renderCountButtons() { let c = getEl('countButtons'); if(!c) return; let counts = [10,20,30,50,'all'], labels = ['১০','২০','৩০','৫০','সব']; c.innerHTML = ''; for(let i=0;i<counts.length;i++) { let btn = document.createElement('button'); btn.type='button'; btn.className='count-btn'; btn.textContent=labels[i]; btn.dataset.count=counts[i]; btn.addEventListener('click',()=>{ currentFilters.count = counts[i]; updateCountVisuals(); updatePreview(); }); c.appendChild(btn); } updateCountVisuals(); }
  function updateCountVisuals() { let c = getEl('countButtons'); if(!c) return; let btns = c.querySelectorAll('.count-btn'); for(let btn of btns) { let active = String(btn.dataset.count) === String(currentFilters.count); btn.classList.toggle('active', active); } }
  function initRandomToggle() { let toggle = getEl('randomToggle'); if(!toggle) return; toggle.checked = currentFilters.random; toggle.addEventListener('change',()=>{ currentFilters.random = toggle.checked; }); }
  function getBaseFilteredQuestions() { if(!window.FilterEngine || !allQuestions.length) return []; return FilterEngine.applyFilters(allQuestions, { subjects: currentFilters.subjects, units: currentFilters.units, types: currentFilters.types, difficulties: currentFilters.difficulties, multi: currentFilters.multi, random: false, count: 'all' }); }
  function updatePreview() { if(!window.FilterEngine || !allQuestions.length) return; let filtered = getBaseFilteredQuestions(); if(window.FilterHistory && currentFilters.history !== 'all') filtered = FilterHistory.filterByHistory(filtered, currentFilters.history); let matchCount = filtered.length; let quizCount = currentFilters.count === 'all' ? matchCount : Math.min(matchCount, parseInt(currentFilters.count,10) || 20); if(getEl('matchCount')) getEl('matchCount').textContent = toBengali(matchCount); if(getEl('quizCount')) getEl('quizCount').textContent = toBengali(quizCount); let startBtn = getEl('startQuizBtn'); if(startBtn) { if(matchCount === 0) { startBtn.disabled = true; startBtn.textContent = 'কোনো প্রশ্ন পাওয়া যায়নি'; } else { startBtn.disabled = false; startBtn.textContent = `কুইজ শুরু করুন (${toBengali(quizCount)}টি প্রশ্ন)`; } } let breakdownEl = getEl('breakdownList'); if(breakdownEl) { breakdownEl.innerHTML = ''; if(matchCount === 0) breakdownEl.innerHTML = '<span class="breakdown-empty">ফিল্টার পরিবর্তন করুন</span>'; else { let breakdown = FilterEngine.getBreakdown(filtered); let selectedSubjects = currentFilters.subjects.includes('all') ? FilterEngine.getAllSubjects() : currentFilters.subjects; for(let sub of selectedSubjects) { if(!breakdown[sub]) breakdown[sub] = { count: 0, multiCount: 0 }; } for(let sub in breakdown) { let data = breakdown[sub]; let count = typeof data === 'object' ? data.count : data; let multiCount = typeof data === 'object' ? data.multiCount : 0; let color = FilterEngine.getSubjectColor(sub); let pill = document.createElement('span'); pill.className = 'breakdown-pill'; if(count === 0 && emptySubjects.indexOf(sub) !== -1) { pill.style.backgroundColor = '#f5f5f5'; pill.style.borderColor = '#ccc'; pill.style.color = '#999'; } else { pill.style.backgroundColor = color + '20'; pill.style.borderColor = color; pill.style.color = color; } pill.textContent = `${FilterEngine.getSubjectBn(sub)}: ${toBengali(count)}` + (multiCount ? ` (${toBengali(multiCount)} বহু-সঠিক)` : ''); breakdownEl.appendChild(pill); } let totalMulti = filtered.filter(q => q && q.multi === true).length; if(totalMulti) { let mpill = document.createElement('span'); mpill.className = 'breakdown-pill breakdown-pill--multi'; mpill.textContent = `☑ মোট বহু-সঠিক: ${toBengali(totalMulti)}`; breakdownEl.appendChild(mpill); } } } }
  function startQuiz() { if(!window.FilterEngine) return; let filtered = FilterEngine.applyFilters(allQuestions, { subjects: currentFilters.subjects, units: currentFilters.units, types: currentFilters.types, difficulties: currentFilters.difficulties, multi: currentFilters.multi, random: false, count: 'all' }); if(window.FilterHistory && currentFilters.history !== 'all') filtered = FilterHistory.filterByHistory(filtered, currentFilters.history); if(currentFilters.random) filtered = FilterEngine.shuffleArray(filtered); if(currentFilters.count !== 'all') { let limit = parseInt(currentFilters.count,10) || 20; filtered = filtered.slice(0, limit); } if(!filtered.length) { alert('কোনো প্রশ্ন পাওয়া যায়নি। ফিল্টার পরিবর্তন করুন।'); return; } try { sessionStorage.setItem('filter_quiz_questions', JSON.stringify(filtered)); sessionStorage.setItem('filter_quiz_config', JSON.stringify(currentFilters)); window.location.href = './filter-quiz.html'; } catch(e) { alert('কুইজ শুরু করতে সমস্যা। পেজ রিলোড করুন।'); } }
  function updateStatsBar() { let statsEl = getEl('totalLoadedText'); if(!statsEl) return; let realQuestions = allQuestions.filter(q => emptySubjects.indexOf(q._subject) === -1); let totalMulti = realQuestions.filter(q => q.multi === true).length; let text = `মোট ${toBengali(realQuestions.length)}টি প্রশ্ন • ৬টি বিষয়` + (totalMulti ? ` • ${toBengali(totalMulti)}টি বহু-সঠিক` : ''); if(emptySubjects.length) text += ` (⚠️ ${emptySubjects.map(s => FilterEngine.getSubjectBn(s)).join(', ')} - 0)`; statsEl.textContent = text; }
  async function initFilterApp() { if(!window.FilterLoader || !window.FilterEngine) { showError('FilterLoader বা FilterEngine লোড হয়নি।'); return; } showLoading(true); try { allQuestions = await window.FilterLoader.loadAllQuestions((l,t) => updateLoadingProgress(l,t)); } catch(e) { showError('প্রশ্ন লোড করতে সমস্যা: '+e.message); return; } emptySubjects = allQuestions.emptySubjects || []; if(!allQuestions.length) { showError('কোনো প্রশ্ন লোড হয়নি।'); return; } showLoading(false); renderSubjectFilters(); renderUnitFilters(); renderTypeFilters(); renderDifficultyFilters(); renderMultiFilters(); renderHistoryFilters(); renderCountButtons(); initRandomToggle(); updateStatsBar(); updateHistoryStats(); updatePreview(); }
  document.addEventListener('DOMContentLoaded', () => { let startBtn = getEl('startQuizBtn'); if(startBtn) startBtn.addEventListener('click', startQuiz); let retryBtn = getEl('retryBtn'); if(retryBtn) retryBtn.addEventListener('click', () => location.reload()); let clearCacheBtn = getEl('clearCacheBtn'); if(clearCacheBtn && window.FilterLoader) { clearCacheBtn.addEventListener('click', () => { if(confirm('সব ক্যাচ ডাটা মুছে ফেলে নতুন করে লোড করবেন?')) { window.FilterLoader.clearCache(); location.reload(); } }); } initFilterApp(); });
  window._FilterApp = { getAllQuestions: () => allQuestions, getCurrentFilters: () => currentFilters, reInit: initFilterApp };
})(window);